# Generated by Django 3.1.2 on 2020-10-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20201030_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='election',
        ),
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ManyToManyField(to='votes.Election'),
        ),
    ]
