# Generated by Django 3.1.2 on 2020-10-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_auto_20201030_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='elections',
            field=models.ManyToManyField(to='votes.Election'),
        ),
    ]
