# Generated by Django 3.1.2 on 2020-11-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0011_auto_20201101_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='seats',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
